/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyzeTab: typeof import('./src/components/AnalyzeTab.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PlayerTab: typeof import('./src/components/PlayerTab.vue')['default']
  }
}
